----Multitable Inserts----
--Use INSERT ALL command

select * from customer1;

INSERT ALL 
  INTO CUSTOMER1(CUSTOMERID,NAME) VALUES (7,'RAM')
  INTO CUSTOMER1(CUSTOMERID,NAME) VALUES (8,'MIKE')
  INTO CUSTOMER1(CUSTOMERID,NAME) VALUES (9,'MIKKY')
SELECT * FROM DUAL;

select * from customer1;

SELECT * FROM SALES;

INSERT ALL
  INTO SALES(SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT)
  VALUES ('24-FEB-2017',3445,233,12,2000,1,555,555,120,675)
  INTO CUSTOMER1(CUSTOMERID,NAME) VALUES (10,'CUNNY')
SELECT * FROM DUAL;

select * from customer1;

SELECT * FROM SALES;